export const APP_ON_INITIALIZE_REQUESTED = 'APP_ON_INITIALIZE_REQUESTED';
export const APP_ON_INITIALIZE_SUCCESS = 'APP_ON_INITIALIZE_SUCCESS';
export const APP_ON_INITIALIZE_FAILED = 'APP_ON_INITIALIZE_FAILED';
